title: Immersive Animal Anatomy Visualizer
description: With the practical/logistical challenges inherent to acquiring cadavers, and the limintations of studying 3 dimensional structures from a textbook, there exists a need for a portable, convenient tool to provide students regular "hands-on" learning. This is the aim of the Immersive Animal Anatomy Visualizer.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman